### ISSUE TITLE
训练集的格式

### ISSUE THREAD

**Issue by wxl-lxw** [yjs1224/TextSteganalysis#3]
您好，我想用自己的训练集来进行隐写分析，请问我应该怎样将训练集排版，把它设置成什么样的格式呢？

**Comment by yjs1224** [comment]
参考config.dataset 参数。可以指定stego cover的txt文件地址，每行一条文本。也可以使用csv文件，每行为文本，label的pair，这种情况下需要划分train dev test set，分别用三个csv文件存储，然后使用csv_dir参数指定存储上述三个csv文件的文件夹地址
