### ISSUE TITLE
礼貌讨论

### ISSUE THREAD

**Issue by nhp310** [yjs1224/TextSteganalysis#4]

**Comment by yjs1224** [comment]
有事儿说事儿。

“写个嵌套加载config以为自己很牛，你看看能load么”啥意思？哪一行代码，代码有bug自然会修改。

“csv.writer多少年的bug了，newline不知道加。” 这个还真不知道，在我们提供的数据集样例下，可以运行。

“args和Configs不知道用哪个就别隔着写两个变量。” 有没有一种可能，开源代码没有终身责任制。有没有一种可能，Configs是用来管理模型超参数的，args是用来方便脚本调用的。
